name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Créer requirements.txt temporaire
        run: |
          echo "pygame" >> requirements.txt
          echo "pytest" >> requirements.txt

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Ajouter le chemin source (pour les imports)
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Lancer les tests
        run: pytest tests/
